# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否员工'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否超级用户'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel',
            field=models.CharField(max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
