# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160811_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (0, '女')], null=True, verbose_name='性别'),
        ),
    ]
