# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160812_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='超级用户'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
