# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
