# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160921_0001'),
        ('welcome', '0002_auto_20160921_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmember',
            name='department',
        ),
        migrations.AddField(
            model_name='newmember',
            name='department',
            field=models.ManyToManyField(blank=True, to='account.Department', verbose_name='部门'),
        ),
    ]
