# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20160924_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='birth',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='newmember',
            name='qq',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='qq'),
        ),
    ]
